name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --load -t debian-builder .
          docker run --name debian-builder-container -v ${{ github.workspace }}:/data  debian-builder

      - name: Get package permalink
        run: |
          date > release.txt
          for file in $(ls -1 release/*.deb); do
              echo "- ${file##*/}: \`$(sha256sum ${file} | cut -d' ' -f1)\`" >> release.txt
          done
          for file in $(ls -1 release/*.tgz); do
              echo "- ${file##*/}: \`$(sha256sum ${file} | cut -d' ' -f1)\`" >> release.txt
          done

      - name: Deploy deb to Fury
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          for file in $(ls -1 release/*.deb); do
              curl -F "package=@$file"  https://${FURY_TOKEN}@push.fury.io/machsix/
          done

      - name: Create release by uploading all the files in release folder
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: release/*
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: release.txt
          make_latest: true
          draft: false
          prerelease: false
